import sqlite3

conn = sqlite3.connect('collegedataboard.db')

conn.execute('''CREATE TABLE schools
    (
    name  VARCHAR       NOT NULL,
    website VARCHAR     NOT NULL,
    location VARCHAR,
    setting VARCHAR,
    size VARCHAR,
    pp VARCHAR,
    rate VARCHAR,
    ED VARCHAR,
    app VARCHAR,
    st VARCHAR,
    SATm VARCHAR,
    SATl VARCHAR,
    SAT VARCHAR,
    sts VARCHAR,
    ABcalc VARCHAR,
    BCcalc VARCHAR,
    chem VARCHAR,
    csa VARCHAR,
    csp VARCHAR,
    gov VARCHAR,
    lang VARCHAR,
    lit VARCHAR,
    econ VARCHAR,
    phy1 VARCHAR,
    phyC VARCHAR,
    stats VARCHAR,
    apush VARCHAR,
    whap VARCHAR,
    tuition VARCHAR,
    avgAid VARCHAR,
    rcvAid VARCHAR,
    bracket VARCHAR
     );''')

conn.execute('''INSERT INTO schools VALUES
    ("Massachusetts Institute of Technology",
    "http://web.mit.edu/",
    "Cambridge, Massachusetts",
    "City",
    "4,476 students (Medium)",
    "Private",
    "7.9%",
    "Early Action",
    "No",
    "two: one in math (level 1 or 2), and one in science (physics, chemistry, or biology e/m)",
    "770-800",
    "730-780",
    "1500-1580",
    "Math: 760-800<br>Science: 740-800",
    "5",
    "5",
    "none",
    "none",
    "none",
    "5",
    "5",
    "5",
    "none",
    "none",
    "5",
    "none",
    "5",
    "5",
    "$67,430",
    "$42,145",
    "91%",
    "$17,992");
''')

conn.execute('''INSERT INTO schools VALUES
    ("Stanford",
    "http://www.stanford.edu/",
    "Stanford, California",
    "Suburban",
    "7,018 students (Medium)",
    "Private",
    "4.8%",
    "Restrictive Early Action (Applicants do not apply to any other <strong>private</strong> college/university under their Early Action, Restrictive Early Action, Early Decision or Early Notification program.)",
    "Yes",
    "Recommended",
    "700-790",
    "680-780",
    "1380-1570",
    "???",
    "5",
    "4",
    "5",
    "4",
    "4",
    "none",
    "none",
    "none",
    "none",
    "4",
    "4",
    "none",
    "none",
    "none",
    "$64,477",
    "$50,547",
    "100%",
    "$18,212");
''')


conn.execute('''INSERT INTO schools VALUES
    ("Carnegie Mellon",
    "http://www.cmu.edu/",
    "Pittsburgh, Pennsylvania",
    "City",
    "5,819 students (Medium)",
    "Private",
    "13.7%",
    "Early Decision",
    "Yes",
    "Recommended (School of Computer Science: Math Level II and
Physics, Chemistry or Biology)",
    "700-800",
    "650-750",
    "1350-1550",
    "???",
    "4",
    "5",
    "5",
    "4",
    "4",
    "4",
    "5",
    "5",
    "5",
    "none",
    "5",
    "4",
    "5",
    "5",
    "$68,452",
    "$41,636",
    "98%",
    "$29,800");
''')




conn.commit()
conn.close()
