import sqlite3

conn = sqlite3.connect('collegedataboard.db')

conn.execute('''CREATE TABLE schools
    (
    name  VARCHAR       NOT NULL,
    website VARCHAR     NOT NULL,
    location VARCHAR,
    setting VARCHAR,
    size VARCHAR,
    pp VARCHAR,
    rate VARCHAR,
    ED VARCHAR,
    app VARCHAR,
    st VARCHAR,
    SATm VARCHAR,
    SATl VARCHAR,
    SAT VARCHAR,
    sts VARCHAR,
    ABcalc VARCHAR,
    BCcalc VARCHAR,
    chem VARCHAR,
    csa VARCHAR,
    csp VARCHAR,
    gov VARCHAR,
    lang VARCHAR,
    lit VARCHAR,
    econ VARCHAR,
    phy1 VARCHAR,
    phyC VARCHAR,
    stats VARCHAR,
    apush VARCHAR,
    whap VARCHAR,
    tuition VARCHAR,
    avgAid VARCHAR,
    rcvAid VARCHAR,
    bracket VARCHAR,
    USr VARCHAR,
    niR VARCHAR,
    bvsR VARCHAR,
    ccnR VARCHAR
     );''')

conn.execute('''INSERT INTO schools VALUES
    ("Massachusetts Institute of Technology",
    "http://web.mit.edu/",
    "Cambridge, Massachusetts",
    "City",
    "04,476 students (Medium)",
    "Private",
    "07.9%",
    "Early Action",
    "No",
    "Required.<br>one in math (level 1 or 2), and one in science (physics, chemistry, or biology e/m)",
    "770-800",
    "730-780",
    "1500-1580",
    "Math: 760-800<br>Science: 740-800",
    "5",
    "5",
    "none",
    "none",
    "none",
    "5",
    "5",
    "5",
    "none",
    "none",
    "5",
    "none",
    "5",
    "5",
    "$67,430",
    "$42,145",
    "91%",
    "$17,992",
    "#01",
    "#01",
    "#02",
    "#02");
''')

conn.execute('''INSERT INTO schools VALUES
    ("Stanford",
    "http://www.stanford.edu/",
    "Stanford, California",
    "Suburban",
    "07,018 students (Medium)",
    "Private",
    "04.8%",
    "Restrictive Early Action (Applicants do not apply to any other <strong>private</strong> college/university under their Early Action, Restrictive Early Action, Early Decision or Early Notification program.)",
    "Yes",
    "Recommended.",
    "700-790",
    "680-780",
    "1380-1570",
    "???",
    "5",
    "4",
    "5",
    "4",
    "4",
    "none",
    "none",
    "none",
    "none",
    "4",
    "4",
    "none",
    "none",
    "none",
    "$64,477",
    "$50,547",
    "100%",
    "$18,212",
    "#02",
    "#02",
    "#03",
    "#07");
''')


conn.execute('''INSERT INTO schools VALUES
    ("Carnegie Mellon",
    "http://www.cmu.edu/",
    "Pittsburgh, Pennsylvania",
    "City",
    "05,819 students (Medium)",
    "Private",
    "13.7%",
    "Early Decision",
    "Yes",
    "Recommended.<br>School of Computer Science: Math Level II and
Physics, Chemistry or Biology",
    "700-800",
    "650-750",
    "1350-1550",
    "???",
    "4",
    "5",
    "5",
    "4",
    "4",
    "4",
    "5",
    "5",
    "5",
    "none",
    "5",
    "4",
    "5",
    "5",
    "$68,452",
    "$41,636",
    "98%",
    "$29,800",
    "#05",
    "#03",
    "#07",
    "#05");
''')


conn.execute('''INSERT INTO schools VALUES
    ("University of California-Berkeley",
    "http://www.berkeley.edu/",
    "Berkeley, California",
    "City",
    "27,126 students (Large)",
    "Public",
    "17.5%",
    "No",
    "No",
    "Required.<br>College of Chemistry and College of Engineering: Math Level 2 and a science test (Biology E/M, Chemistry, or Physics) closely related to the applicant's intended major.",
    "640-770",
    "610-740",
    "1250-1510",
    "???",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "$61,654",
    "$17,284",
    "98.6%",
    "$20,722",
    "#03",
    "#14",
    "#08",
    "#01");
''')


conn.execute('''INSERT INTO schools VALUES
    ("Georgia Institute of Technology",
    "http://www.gatech.edu/",
    "Atlanta, Georgia",
    "City",
    "13,996 students (Medium)",
    "Public",
    "25%",
    "Early Action",
    "Yes",
    "Optional.<br>If you have taken any of these tests before you apply, you are welcome to submit them if you think they support your application.",
    "680-770",
    "630-730",
    "1360-1490",
    "???",
    "4",
    "4",
    "4",
    "4",
    "none",
    "4",
    "4",
    "4",
    "4",
    "4",
    "5",
    "none",
    "4",
    "4",
    "$48,566",
    "$13,854",
    "94.0%",
    "$13,736",
    "#06",
    "#08",
    "#04",
    "#04");
''')


conn.execute('''INSERT INTO schools VALUES
    ("Cornell",
    "https://www.cornell.edu/",
    "Ithaca, New York",
    "City",
    "14,195 students (Medium)",
    "Private",
    "14.1%",
    "Early Decision",
    "Yes",
    "Required.<br>Engineering: Mathematics (any level) and a science of your choice<br>Arts and Sciences: Two subjects of your choice",
    "680-770",
    "650-740",
    "1330-1510",
    "???",
    "4",
    "4",
    "5",
    "5",
    "none",
    "none",
    "4",
    "4",
    "4",
    "5",
    "5",
    "4",
    "4",
    "4",
    "$67,613",
    "100%",
    "100%",
    "$26,486",
    "#09",
    "#18",
    "#10",
    "#27");
''')
# CS = college of arts + science OR college of engineering



conn.execute('''INSERT INTO schools VALUES
    ("University of Michigan",
    "http://www.umich.edu/",
    "Ann Arbor, Michigan",
    "City",
    "28,217 students (Large)",
    "Public",
    "28.6%",
    "Early Action",
    "Yes",
    "Optional.<br>You will not be penalized for low SAT subject test scores since they are not a required component of a complete application.",
    "660-760",
    "620-720",
    "1280-1570",
    "???",
    "5",
    "4",
    "4",
    "4",
    "4",
    "3",
    "4",
    "4",
    "4",
    "5",
    "5",
    "4",
    "4",
    "4",
    "$59,784",
    "89%",
    "95.6%",
    "$18,251",
    "#07",
    "#20",
    "#19",
    "#08");
''')



conn.commit()
conn.close()
